<?php

namespace MalikAd778\BladeAlly\Support;

class AriaRoleDefinitions
{
    public static function getRoles(): array
    {
        return [
            'alert' => [],
            'alertdialog' => ['aria-label', 'aria-labelledby'],
            'application' => ['aria-label', 'aria-labelledby'],
            'article' => ['aria-label', 'aria-labelledby'],
            'banner' => [],
            'button' => ['aria-label', 'aria-labelledby', 'aria-pressed', 'aria-expanded'],
            'cell' => [],
            'checkbox' => ['aria-checked'],
            'columnheader' => [],
            'combobox' => ['aria-expanded', 'aria-controls'],
            'complementary' => [],
            'contentinfo' => [],
            'definition' => ['aria-label', 'aria-labelledby'],
            'dialog' => ['aria-label', 'aria-labelledby'],
            'directory' => ['aria-label', 'aria-labelledby'],
            'document' => ['aria-label', 'aria-labelledby'],
            'feed' => ['aria-label', 'aria-labelledby'],
            'figure' => ['aria-label', 'aria-labelledby'],
            'form' => ['aria-label', 'aria-labelledby'],
            'grid' => ['aria-label', 'aria-labelledby'],
            'gridcell' => [],
            'group' => ['aria-label', 'aria-labelledby'],
            'heading' => ['aria-level'],
            'img' => ['aria-label', 'aria-labelledby'],
            'link' => ['aria-label', 'aria-labelledby', 'aria-expanded'],
            'list' => ['aria-label', 'aria-labelledby'],
            'listbox' => ['aria-label', 'aria-labelledby'],
            'listitem' => ['aria-level', 'aria-posinset', 'aria-setsize'],
            'log' => ['aria-label', 'aria-labelledby'],
            'main' => [],
            'marquee' => ['aria-label', 'aria-labelledby'],
            'math' => ['aria-label', 'aria-labelledby'],
            'menu' => ['aria-label', 'aria-labelledby'],
            'menubar' => ['aria-label', 'aria-labelledby'],
            'menuitem' => ['aria-label', 'aria-labelledby'],
            'menuitemcheckbox' => ['aria-checked'],
            'menuitemradio' => ['aria-checked'],
            'navigation' => ['aria-label', 'aria-labelledby'],
            'none' => [],
            'note' => ['aria-label', 'aria-labelledby'],
            'option' => ['aria-selected'],
            'presentation' => [],
            'progressbar' => ['aria-label', 'aria-labelledby', 'aria-valuenow'],
            'radio' => ['aria-checked'],
            'radiogroup' => ['aria-label', 'aria-labelledby'],
            'region' => ['aria-label', 'aria-labelledby'],
            'row' => [],
            'rowgroup' => [],
            'rowheader' => [],
            'scrollbar' => ['aria-label', 'aria-labelledby', 'aria-valuenow'],
            'search' => ['aria-label', 'aria-labelledby'],
            'searchbox' => ['aria-label', 'aria-labelledby'],
            'separator' => ['aria-label', 'aria-labelledby', 'aria-valuenow'],
            'slider' => ['aria-label', 'aria-labelledby', 'aria-valuenow'],
            'spinbutton' => ['aria-label', 'aria-labelledby', 'aria-valuenow'],
            'status' => ['aria-label', 'aria-labelledby'],
            'switch' => ['aria-label', 'aria-labelledby', 'aria-checked'],
            'tab' => ['aria-selected'],
            'table' => ['aria-label', 'aria-labelledby'],
            'tablist' => ['aria-label', 'aria-labelledby'],
            'tabpanel' => ['aria-label', 'aria-labelledby'],
            'term' => ['aria-label', 'aria-labelledby'],
            'textbox' => ['aria-label', 'aria-labelledby'],
            'timer' => ['aria-label', 'aria-labelledby'],
            'toolbar' => ['aria-label', 'aria-labelledby'],
            'tooltip' => ['aria-label', 'aria-labelledby'],
            'tree' => ['aria-label', 'aria-labelledby'],
            'treegrid' => ['aria-label', 'aria-labelledby'],
            'treeitem' => ['aria-label', 'aria-labelledby'],
        ];
    }
}
